spring.application.name=financeflow

# Conexão com o PostgreSQL local
spring.datasource.url=jdbc:postgresql://localhost:5432/financeflow
spring.datasource.username=financeflow
spring.datasource.password=financeflow

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.open-in-view=false